export const professions = [
  '📈 Finance & Trading',
  '⚖️ Legal',
  '💻 Technology',
  '🩺 Healthcare',
  '💼 Consulting',
  '📣 Marketing & Media',
  '🏛️ Government & Policy',
  '🏢 Real Estate',
  '🎓 Education',
  '🚀 Founder / Builder',
];
export const niches = [
  '🤖 AI & Technology',
  '📊 Financial Markets',
  '🇮🇳 Indian Business',
  '🌍 Global Politics',
  '🚀 Startups',
  '🔬 Science',
  '🗺️ Geopolitics',
  '💊 Health & Medicine',
  '🌱 Climate & Energy',
  '⚽ Sports',
  '🎨 Culture & Arts',
  '⚖️ Legal & Policy',
];
export const topicMap = [
  'Technology',
  'Business',
  'Business',
  'Culture',
  'Business',
  'Science',
  'Culture',
  'Health',
  'Science',
  'Sports',
  'Culture',
  'Business',
];
export const voices = [
  {
    name: 'Aria',
    tag: 'EN',
    description: 'Warm · Unhurried · British, ♀',
    language: 'English',
    color: 'aria',
  },
  {
    name: 'Kal',
    tag: 'EN',
    description: 'Crisp · Focused · American, ♂',
    language: 'English',
    color: 'kal',
  },
  {
    name: 'Meera',
    tag: 'HI',
    description: 'Bright · Curious · Indian, ♀',
    language: 'Hindi',
    color: 'meera',
  },
];
export const defaults = {
  language: 'English',
  profession: '💻 Technology',
  niches: ['🤖 AI & Technology', '🇮🇳 Indian Business', '🚀 Startups'],
  voice: 'Aria',
  length: '5 min',
  time: '7:00',
  period: 'AM',
  autoAdvance: true,
  notifications: false,
  theme: 'dark',
};
