// Shared by the database seed and the account-free mobile preview.
import { categories } from './categories.js';
export { categories } from './categories.js';
const rows = [
  ['AI & Tech', 'A more thoughtful relationship with artificial intelligence', 'A fictional design studio explores how AI can help with research while people keep the final creative decisions.', 'The studio starts with a small experiment: using an assistant to organize research notes. Designers review every suggestion and keep a record of what they changed.\n\nThe exercise highlights a useful habit: treat generated answers as a starting point, then check them against the original material.'],
  ['AI & Tech', 'A pocket-sized assistant for your morning routine', 'Meet a concept app that turns a busy reading list into a short, personalised audio briefing.', 'In this demo scenario, a reader chooses three interests and a preferred listening time. The app groups related stories and builds a compact queue.\n\nA clear transcript and saved-story list help the reader return to an idea after the audio ends.'],
  ['Markets', 'A beginner’s guide to reading a market dashboard', 'An educational walkthrough of price changes, volume, and the difference between a snapshot and a trend.', 'Our fictional dashboard shows an index moving up one day and down the next. Looking at a longer period changes the picture.\n\nThis sample explains interface terms rather than recommending an investment. No prices or returns here describe a live market.'],
  ['Markets', 'Why earnings-day headlines need a second look', 'A sample company report shows how revenue, costs, and expectations can tell different stories.', 'The imaginary company Northstar reports growing sales alongside higher operating costs. One headline focuses on growth; another focuses on margins.\n\nReading the underlying report gives context that a single headline cannot provide. These company details are fictional.'],
  ['Startups', 'Small teams test big ideas with neighborhood pilots', 'A fictional delivery startup tries a single-street pilot before expanding its service.', 'The team invites a handful of local shops to try a shared collection schedule. Interviews reveal that predictable pickup times matter more than another dashboard.\n\nAfter the pilot, the founders simplify their product and document the questions they still need to answer.'],
  ['Startups', 'From campus project to first customer conversation', 'Three imaginary student founders trade a long feature list for a week of listening to potential users.', 'Their first prototype helps clubs coordinate equipment bookings. Early conversations surface a simpler problem: people do not know who has the keys.\n\nThe next version focuses on a shared handover log, illustrating how customer feedback can reshape an idea.'],
  ['Science', 'The quiet wonder of looking up', 'A beginner’s guide to noticing the night sky, one familiar pattern at a time.', 'Our sample story follows a community observation evening. Participants sketch what they can see and compare notes without needing elaborate equipment.\n\nThe activity centers on patient observation and curiosity, with a plan to return on another clear evening.'],
  ['Science', 'A closer look at the world outside your window', 'A fictional classroom turns everyday observations into a small science journal.', 'Students record cloud shapes, plant growth, and the timing of shadows. They write down questions before attempting explanations.\n\nComparing observations over several days gives the class a practical introduction to keeping consistent records.'],
  ['Indian Business', 'Local shops experiment with a shared digital catalog', 'An imaginary merchants’ association builds a simple way for neighbors to discover nearby stores.', 'Each participating shop contributes a short description and opening hours. The pilot avoids complex ordering features until the group understands demand.\n\nThe sample highlights the practical work behind a useful directory: keeping information current and making corrections easy.'],
  ['Indian Business', 'A family workshop brings its story online', 'A fictional craft business documents its process to help customers understand the work behind each piece.', 'The workshop photographs materials and explains how custom orders are planned. Customers can see the steps involved before making an inquiry.\n\nThis demo explores storytelling and clear communication, without making claims about a real company.'],
  ['Global Politics', 'How a citizens’ forum makes room for different views', 'An imaginary town tests small discussion groups before a public planning meeting.', 'A facilitator gives each group the same background material and time to ask questions. Participants record both agreements and unresolved concerns.\n\nThe resulting summary shows how a structured discussion can capture more than a simple vote count.'],
  ['Global Politics', 'Reading an election explainer beyond the headline', 'A fictional civic guide separates voting rules, campaign promises, and commentary.', 'The guide uses clearly labeled sections so readers can distinguish procedures from opinions. Links to source documents sit alongside each factual summary.\n\nThis is an interface demonstration and does not describe an actual election or current voting rules.'],
  ['Geopolitics', 'Mapping the journey of an everyday product', 'A sample supply-chain map follows a fictional product across several regions.', 'The map separates raw materials, assembly, shipping, and retail. It illustrates why a delay at one stage can affect the rest of the journey.\n\nAll routes and company names in this scenario are invented for the demonstration.'],
  ['Geopolitics', 'Why regional cooperation starts with shared questions', 'An imaginary cross-border workshop brings researchers together around water monitoring.', 'Participants first compare how they collect and label their measurements. Agreeing on definitions becomes an important part of making the data useful.\n\nThe sample explores collaboration without reporting on a real diplomatic event.'],
  ['Health & Medicine', 'Making room for a calmer daily routine', 'A fictional reader experiments with a less crowded calendar and a regular screen break.', 'The reader starts by noting which parts of the day feel rushed. Rather than changing everything at once, they reserve a short pause between tasks.\n\nThis is a lifestyle story for demonstration, not medical advice or a claim about health outcomes.'],
  ['Health & Medicine', 'Designing clearer information for a clinic waiting room', 'An imaginary clinic tests plain-language signs and a simpler appointment checklist.', 'Visitors help the team identify confusing labels and missing directions. The revised signs describe where to go and whom to ask for help.\n\nThe exercise focuses on communication and accessibility, not diagnosis or treatment.'],
  ['Climate & Energy', 'A neighborhood explores its energy habits', 'A fictional community group creates a shared notebook of everyday energy questions.', 'Residents list the appliances and routines they want to understand better. The group invites questions before discussing possible changes.\n\nThe sample contains no measured savings or claims about a real energy project.'],
  ['Climate & Energy', 'Repair cafés give familiar objects another chapter', 'An imaginary weekend event brings volunteers together to examine repairable household items.', 'Visitors describe what stopped working while volunteers explain what they can safely inspect. Items needing specialist work are set aside for professional attention.\n\nThe story centers on learning and reuse rather than promising a repair for every object.'],
  ['Sports', 'The communities behind the starting line', 'A fictional running club welcomes newcomers with a conversation-paced weekend route.', 'The organizers publish clear meeting details and several route options. A volunteer stays with each group so nobody has to guess where to go.\n\nThe sample celebrates the social side of local sport without reporting a real competition.'],
  ['Sports', 'A local league puts the spotlight on volunteers', 'An imaginary community tournament recognizes the people who keep match day running.', 'Before the first game, volunteers check the schedule, prepare the venue, and answer visitors’ questions. Their planning makes the event easier to navigate.\n\nThe names, teams, and event in this story are fictional.'],
  ['Culture & Arts', 'Rediscovering the joy of your local library', 'A fictional library opens a small reading corner for neighborhood recommendations.', 'Readers leave handwritten notes about books they enjoyed. The display connects familiar favorites with titles someone else might never have picked up.\n\nThe sample explores how a shared cultural space can encourage discovery.'],
  ['Culture & Arts', 'An evening of sketches, stories, and familiar streets', 'An imaginary arts walk invites neighbors to see everyday places through a different lens.', 'Participants stop at a market, a courtyard, and a quiet corner to sketch or write. There is no competition; the aim is to notice something new.\n\nAt the end, the group shares its work in a temporary community display.'],
  ['Legal & Policy', 'A plain-language guide to understanding public proposals', 'A fictional policy portal puts summaries, source documents, and feedback dates in one place.', 'Each proposal page separates the current situation from the suggested change. Readers can compare the summary with the full document before responding.\n\nThis is a product scenario, not legal advice or a description of current legislation.'],
  ['Legal & Policy', 'Making a privacy notice easier to navigate', 'An imaginary app groups its data explanations around the questions users actually ask.', 'The prototype explains what information is collected, why it is needed, and how a user can request changes. Short sections link to more detailed explanations.\n\nThe story demonstrates a clearer reading experience and does not assess legal compliance.'],
];
export const demoStories = rows.map(([category, title, summary, content], index) => ({
  slug: `demo-${category.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${index % 2 + 1}`,
  audioUrl: `/audio/demo-${category.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${index % 2 + 1}.mp3`,
  category, topic: categories.find(item => item.label === category).topic,
  title, summary, content: `${content}\n\nDemo story: fictional content created to explore Nuzio. Not a current news report.`,
  source: 'NUZIO DEMO', readMinutes: index % 2 + 2, demo: true,
  publishedAt: new Date(Date.UTC(2026, 8, 18, 8, 0) - index * 3600000).toISOString(),
}));
